### ISSUE TITLE
Can status code be overridden?

### ISSUE THREAD

**Issue by ayushmanchhabra** [Pasupathi-Rajamanickam/chrome-response-override#11]
Is it possible to override a response and change the status code to 401?

This is what I've tried but since it's not working for me I'm probably not doing it the correct way or maybe it's not possible to via this extension?

<img width="612" alt="image" src="https://user-images.githubusercontent.com/14110965/175394721-c4f4726b-4b8e-4a40-84b9-3a8394a6a8d8.png">

**Comment by Pasupathi-Rajamanickam** [comment]
Submitted 1.8 version in chrome web store, with status code changes. Will update here once published. 
More info here
https://github.com/Pasupathi-Rajamanickam/chrome-response-override/releases/tag/1.8

**Comment by ayushmanchhabra** [comment]
Thanks!
