### ISSUE TITLE
No info about how to start this

### ISSUE THREAD

**Issue by PetrKnedlik** [Pasupathi-Rajamanickam/chrome-response-override#12]
You should add some information for noobs like me about how to actually set it up. In Readme you are expecting that it's already part of devtools, but in order to get there you need to do some magic before that

**Comment by hkedia321** [comment]
@Pasupathi-Rajamanickam can you please inform us how to install this?

**Comment by Pasupathi-Rajamanickam** [comment]
Added few more info about installation and getting started. Please check readme

https://github.com/Pasupathi-Rajamanickam/chrome-response-override#install-plugin
