### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by ErikSwan** [Pasupathi-Rajamanickam/chrome-response-override#4]
I can't get this extension to work with even a basic find/replace.

I am using Chrome `86.0.4240.75 (Official Build) (64-bit)`.

### Steps to reproduce:
1. Navigate to http://example.com
2. Open Chrome DevTools
3. Navigate to the Response Override tab and add the following row:
    - URL contains: `/`
    - Find: `domain`
    - Replace: `foobar`
    - Content-Type: (empty)
    ![image](https://user-images.githubusercontent.com/163976/95363363-9b5dee00-088c-11eb-81e0-3bea3cc87533.png)
4. Click Save and then the "play" button (`>`)
4. Refresh the page.

### Expected behavior:
I would expect the word "domain" in the page body to be replaced with "foobar".

### Actual behavior:
The word "domain" does not get replaced anywhere in the response content, either in the reponse shown in the Network tab of the DevTools or in the rendered page body itself.

**Comment by Pasupathi-Rajamanickam** [comment]
@ErikSwan 
By any chance do you have modheader or similar extension installed in your chrome? If so can you disable for a moment and try response override?

**Comment by ErikSwan** [comment]
I do not. The only extension I had enabled was `chrome-response-override`. Are you able to reproduce my simple test case?

**Comment by bernatgy** [comment]
Can confirm, the extension just doesn't do anything. (same chrome version here)
Also, description in store says;

> 10) Issue with the override, either open private tab with only this plugin enabled in private tab or please try disabling other plugins working with network, like request header modifier and run this plugin again. If the other plugins using old network API may affect this plugin

I'm guessing you meant an Incognito window. Still doesn't work though.

(with no other extensions at all)

**Comment by ErikSwan** [comment]
For what it's worth, I ended up using [Fiddler](https://www.telerik.com/fiddler) to do what I wanted, which has a similar response-modification feature.

**Comment by Pasupathi-Rajamanickam** [comment]
I'm not able to. It's working on my end. Will try to reproduce and let you know.

**Comment by Pasupathi-Rajamanickam** [comment]
More details why this is happening in here https://github.com/Pasupathi-Rajamanickam/chrome-response-override/issues/7#issuecomment-744062433

The issue talking about example.com which is super simple override, but things getting worse if I use something like google.com 

Will get a fix and publish.

**Comment by Pasupathi-Rajamanickam** [comment]
Fixed URL contains "/" breaking whole page. 
```
If you want to modify URL in home page like www.example.com and no URI Path, use Special variable called ~NO_URI~ in URL contains field.
```
