### ISSUE TITLE
Simple replace the response with user given json possible ?

### ISSUE THREAD

**Issue by DivekJohns** [Pasupathi-Rajamanickam/chrome-response-override#5]
I would like to give a JSON to plugin and that should be responded possible?

**Comment by Pasupathi-Rajamanickam** [comment]
Yes. Please follow this


Special Variable 

1. If you put `"~NO_API~"` (without ") in Find, no remote call will be made, provide full response. Provide content-type in this case.

**Comment by Pasupathi-Rajamanickam** [comment]
Feel free to re-open the issue if the above doesn't work.

**Comment by LoganDark** [comment]
I recently encountered a scenario where find and replace did not work but `~NO_API~` did for some reason
