### ISSUE TITLE
Some of the request headers were missed when enable this extension

### ISSUE THREAD

**Issue by cuitao2046** [Pasupathi-Rajamanickam/chrome-response-override#6]
Hi,

I was trying to modify the response of my http request. The request was used to upload file to remote server.
I noticed that when I enable the extension, the **Content-Length** was set to zero, and thus, server could not properly process the request.
The fisrt snapshot showed you the wrong content-length, the second one was the right one with extension disabled.
![image](https://user-images.githubusercontent.com/10990298/101722031-52bcee00-3ae4-11eb-9281-197596e4b026.png)
![image](https://user-images.githubusercontent.com/10990298/101730812-a5eb6c80-3af5-11eb-850d-cd660516e494.png)

**Comment by cuitao2046** [comment]
![image](https://user-images.githubusercontent.com/10990298/101722031-52bcee00-3ae4-11eb-9281-197596e4b026.png)

**Comment by Pasupathi-Rajamanickam** [comment]
Will check and update. Thanks for reporting.

**Comment by cuitao2046** [comment]
> Will check and update. Thanks for reporting.

Thank you! 
BTW, I forgot to mention that the method of the request was POST as you may have known of it.
